email_bot/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout_then_login
from email_bot.views import OLTemplateView, OLHomeView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'oneleap_email_bot.views.home', name='home'),
    # url(r'^oneleap_email_bot/', include('oneleap_email_bot.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('introductions.urls')),
    url(r'', include('invitation.urls')),
    url(r'', include('email_integration.urls')),
    (r'^browserid/', include('django_browserid.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^$', OLHomeView.as_view(template_name="home.html")),
    (r'^pricing$', OLTemplateView.as_view(template_name="pricing.html")),
    (r'^comingsoon$', OLTemplateView.as_view(template_name="comingsoon.html")),
    (r'^dev/introductions$', OLTemplateView.as_view(template_name="introduction.html")),
    (r'^dev/main$', OLTemplateView.as_view(template_name="dashboard.html")),
    (r'^login/?$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url (r'^logout/?$', logout_then_login, name="logout"),
    (r'^account/', include('django.contrib.auth.urls')),
)

introductions/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from .views import *
from .api import *

introduction_resource = IntroductionResource()

urlpatterns = patterns('',
        #url(r'^introductions/?$', login_required(IntroductionListView.as_view())),
    url(r'^dashboard/?$', login_required(IntroductionListView.as_view(template_name="dashboard.html")), name='introduction_dashboard'),
    url(r'^introductions?/followup/(?P<slug>\w+)$', FollowUpUpdate.as_view(template_name="introductions/followup_form.html")),
    url(r'^introductions?/feedback/(?P<slug>\w+)$', FollowUpUpdate.as_view(template_name="introductions/feedback_form.html")),
    url(r'^introductions?/(?P<slug>[\w-]+)$', login_required(IntroductionDetailView.as_view()), name='introduction_detail'),
    url(r'^my/introductions?/(?P<slug>[\w-]+)$', login_required(IntroductionUserDetailView.as_view()), name='introduction_user_detail'),
    url(r'^my/introduction/(?P<slug>[\w-]+)/notify$', login_required(RequestFeedbackFormView.as_view())),
    url(r'^my/profile/?$', login_required(ProfileSettingsView.as_view()), name='introduction_settings'),
    url(r'^my/settings/?$', login_required(ProfilePreferencesView.as_view(template_name="notifications.html")), name='introduction_preferences'),
    url(r'^api/', include(introduction_resource.urls)),
    )

introductions/models.py
import logging
logger = logging.getLogger(__name__)
import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models, IntegrityError, transaction
from django_extensions.db.fields import UUIDField
from email_integration.models import RawEmail, EmailAddress, TemplatedEmailMessage
from email_integration.send_mails import request_feedback_email
import os
import re

class NullableCharField(models.CharField):
    description = "CharField that obeys null=True"

    def get_db_prep_value(self, value, *args, **kwargs):
        my_value = super(NullableCharField, self).get_db_prep_value(value, *args, **kwargs)
        return my_value or None


    def to_python(self, value):
        if isinstance(value, models.CharField):
            return value
        return value or ""

    def get_internal_type(self):
        return "CharField"

    def south_field_triple(self):
        "Returns a suitable description of this field for South"
        # We'll just introspect ourselves, since we inherit.
        from south.modelsinspector import introspector
        field_class = "django.db.models.fields.CharField"
        args, kwargs = introspector(self)
        return (field_class, args, kwargs)


class FollowUpManager(models.Manager):
    def commented(self):
        return super(FollowUpManager, self).all().exclude(comment=None).order_by("-requested")

    def requested(self):
        return super(FollowUpManager, self).all().exclude(requested=None).order_by("-requested")

    def rated(self):
        return super(FollowUpManager, self).all().exclude(rating=None).order_by("-requested")


class FollowUp(models.Model):
    id = UUIDField(primary_key=True, auto=True, version=4)
    name = NullableCharField(max_length=128, null=True)
    email = models.EmailField(max_length=128, null=True)
    other_email = models.EmailField(max_length=128, null=True)
    user = models.ForeignKey(User, null=True)
    introduction = models.ForeignKey('Introduction', editable=False)
    created = models.DateTimeField(auto_now_add=True)
    custom_url = NullableCharField(max_length=64, unique=True, null=True)
    comment = models.TextField(null=True,blank=True)
    requested = models.DateTimeField(null=True, blank=True)
    added = models.DateTimeField(auto_now=True)
    rating = models.PositiveSmallIntegerField(default=75)
    recruiting = models.BooleanField(
            default=False
            )
    partnerships = models.BooleanField(
            default=False
            )
    sales = models.BooleanField(
            default=False
            )
    networking = models.BooleanField(
            default=False
            )
    fundrasing = models.BooleanField(
            default=False
            )
    mentorship = models.BooleanField(
            default=False
            )
    other = models.BooleanField(
            default=False
            )
    toosoon = models.BooleanField(
            default=False
            )
    objects = FollowUpManager()

    class Meta:
        unique_together = ('introduction', 'email')

    def __unicode__(self):
        return "Feedback from %s for %s" % (self.email, self.introduction)

    def request_feedback(self, msg=None):
        to_email = self.email
        connector_name = self.introduction.connector.get_full_name() or self.introduction.from_name
        from_email = "%s via intros.to <%s>" % (connector_name, settings.DEFAULT_FROM_EMAIL)
        other_email = self.other_email
        link = "http://intros.to/introductions/feedback/%s" % self.custom_url
        request_feedback_email(to_email, from_email, connector_name, other_email, msg, link)
        self.requested = datetime.datetime.utcnow()
        self.save()

    def comment_length(self):
        try:
            return len(self.comment)
        except TypeError:
            return 0


class IntroductionManager(models.Manager):
    @transaction.commit_on_success()
    def create_introduction(self, raw_email):
        from_email = raw_email.isolated_from_addr
        connector = None
        try:
            connector = User.objects.get(email=from_email)
        except User.DoesNotExist:
            pass
        if not connector:
            try:
                connector = EmailAddress.objects.get(email_address=from_email).user_profile.user
            except (EmailAddress.DoesNotExist, AttributeError):
                pass
        if not connector:
            # This came from an unregistered user
            # TODO: Send welcome email and invite to join
            print "Can't find a registered user to be the connector for this new message.  From was: %s" % from_email
            return None
        introducee1 = None
        introducee2 = None
        recipients = []
        recipients.extend(raw_email.isolated_to)
        recipients.extend(raw_email.isolated_cc)
        for each in recipients:
            if each != raw_email.isolated_delivered_to:
                if not introducee1:
                    introducee1 = each
                    continue
                if not introducee2:
                    introducee2 = each
                    continue
        last_sequence_dict = self.filter(connector=connector).aggregate(models.Max('sequence'))
        if last_sequence_dict['sequence__max']:
            sequence = last_sequence_dict['sequence__max'] + 1
        else:
            sequence = 1
        intro = Introduction(
            connector = connector,
            email_message = raw_email,
            subject = raw_email.subject,
            message = raw_email.payload,
            introducee1 = introducee1,
            introducee2 = introducee2,
            sequence = sequence
        )
        intro.save()
        logger.debug("Just created an introduction.  It's pk is : %s" % intro.pk)
        if connector.introductionpreferences.auto_send_feedback_requests:
            try:
                email = TemplatedEmailMessage.objects.get(name="IntroductionRegistered")
                email.send(to_email=connector.email, context_dict={'connector_name': connector.get_full_name(), 'introduction':intro })
            except Exception, error:
                pass
                logger.debug("Couldn't send mail announcing an intro made by %s because: %s" % ( connector, error))
        return intro

    def rated(self):
        pkset = set([x.introduction_id for x in FollowUp.objects.commented()])
        return super(IntroductionManager, self).filter(pk__in=pkset)

class Introduction(models.Model):
    id = UUIDField(primary_key=True, auto=True, version=4)
    connector = models.ForeignKey(User)
    introducee1 = models.EmailField()
    introducee2 = models.EmailField()
    subject = NullableCharField(max_length=128, null=True, blank=True)
    message = models.TextField()
    email_message = models.ForeignKey('email_integration.RawEmail', null=True, blank=True, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    sequence = models.IntegerField(default=None, null=True)
    objects = IntroductionManager()

    def get_absolute_url(self):
        return reverse('introduction_detail', args=[str(self.pk)])

    def get_user_url(self):
        return reverse('introduction_user_detail', args=[str(self.sequence)])


    @property
    def feedback_requested(self):
        if len(self.followup_set.requested()) > 0:
            return True
        return False

    @property
    def feedback_commented(self):
        if len(self.followup_set.commented()) > 0:
            return True
        return False

    def __unicode__(self):
        return u'%s introduced %s to %s' % (self.connector, self.introducee1, self.introducee2)

    @property
    def from_name(self):
       return self.email_message.sent_by_name

    @property
    def clean_message(self):
        replacer = re.compile("\n(From|Content-Type:)\ .*\n")
        return replacer.sub('\n',replacer.sub('\n',self.message)).lstrip("\n")

    def create_followups(self):
        followup1 = FollowUp(
            email=self.introducee1,
            other_email=self.introducee2,
            introduction=self,
            custom_url=os.urandom(32).encode('hex')
        )
        try:
            followup1.save()
        except IntegrityError:
            pass
        followup2 = FollowUp(
            email=self.introducee2,
            other_email=self.introducee1,
            introduction=self,
            custom_url=os.urandom(32).encode('hex')
        )
        try:
            followup2.save()
        except IntegrityError:
            pass


class IntroductionProfile(models.Model):
    user         = models.OneToOneField(User)
    location     = models.CharField(max_length=256, blank=True, null=True, default=None)
    headline     = models.CharField(max_length=256, blank=True, null=True, default=None)
    description  = models.CharField(max_length=256, blank=True, null=True, default=None)
    position  = models.CharField(max_length=256, blank=True, null=True, default=None)
    company  = models.CharField(max_length=256, blank=True, null=True, default=None)


class IntroductionPreferences(models.Model):
    user         = models.OneToOneField(User)
    send_gotcha_notifications = models.BooleanField(
            default=True,
            verbose_name="Send me a confirmation email when I bcc my@intros.to"
            )
    send_feedback_notifications = models.BooleanField(
            default=True,
            verbose_name="Notify me when someone leaves me feedback"
            )
    auto_send_feedback_requests = models.BooleanField(
            default=False,
            verbose_name="Automatically request feedback from people I've introduced"
            )
    send_monthly_summary = models.BooleanField(
            default=True,
            verbose_name="Send me a monthly summary of my intros and feedback"
            )


def parse_one_mail(raw_message_id):

introductions/forms.py
import logging
logger = logging.getLogger(__name__)
from django import forms
from .models import FollowUp, IntroductionProfile, IntroductionPreferences

class RangeInput(forms.widgets.Input):
    """HTML5 Range Input"""
    input_type = 'range'


class FollowUpForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = ('comment',
                  'rating',
                  'recruiting',
                  'partnerships',
                  'sales',
                  'networking',
                  'fundrasing',
                  'mentorship',
                  'other',
                  'toosoon')
        widgets = {
            'rating': forms.widgets.HiddenInput(),
            }

class RequestFollowUpForm(forms.Form):
    introducee1_message = forms.CharField (widget=forms.widgets.HiddenInput())
    introducee2_message = forms.CharField (widget=forms.widgets.HiddenInput())
    include_introducee1 = forms.BooleanField(initial=True)
    include_introducee2 = forms.BooleanField(initial=True)


class IntroductionProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=64)
    last_name = forms.CharField(max_length=64)
    error_css_class = "error"
    required_css_class = "required"

    class Meta:
        model = IntroductionProfile
        exclude = ('user',)
        fields = [
                'first_name',
                'last_name',
                'location',
        ]

class IntroductionPreferenceForm(forms.ModelForm):
    error_css_class = "error"
    required_css_class = "required"
    class Meta:
        model = IntroductionPreferences
        exclude = ('user',)

introductions/templates/introductions/_dashboard_list_item.html
        <div class="introitem">
            <div class="row">
                <div class="connectors">
                    <h4>{{ object.introducee1 }} &amp; {{ object.introducee2 }}</h4>
                </div>
            </div>
            <div class="row">
                <div class="introduction">
                    <div class="row">
                        <div class="details">
                            <p class="subject">{{ object.subject|truncatewords:5 }} <span class="date">{{ object.created|timesince }} ago</span></p>
                            <p class="body">{{ object.clean_message|truncatewords:10 }} <a href="{{ object.get_user_url }}">more</a></p>
                        </div>
                        <div class="feedback">
                            <div class="feedback-button">Request Feedback</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--- end of intro item -->

introductions/templates/introductions/_dashboard_list_li_item.html
<h5>{{ object.introducee1 }} <img src="images/icon-arrow-orange.png" alt=""> {{ object.introducee2 }}<span>intro #{{ object.sequence }}</span></h5>
<div class="row">
    <div class="details">
        <p class="subject">{{ object.subject|truncatewords:5 }} <span class="date">{{ object.created|timesince }} ago</span></p>
            <p class="body">{{ object.clean_message|truncatewords:10 }}<a href="{{ object.get_user_url }}">more</a></p>
    </div>
    {% if object.feedback_requested %}
        {% if object.feedback_commented %}
        <div class="feedback">
            <a href="{{ object.get_user_url }}#feedback" class="button radius right medium success">See Feedback</a>
        </div>
        {% else %}
        <div class="feedback">
            <a href="{{ object.get_user_url }}#feedback" class="button radius right medium secondary">Feedback Pending</a>
        </div>
        {% endif %}
    {% else %}
    <div class="feedback">
        <a href="{{ object.get_user_url }}/notify" class="button radius right medium ">Ask for Feedback</a>
    </div>
    {% endif %}
</div>

introductions/templates/introductions/_dashboard_rating_slider.html
<div class="slider-parent">
  <!-- boundingBox -->
  <span class="yui3-widget yui3-sliderbase yui-slider">
      <!-- contentBox -->
      <span class="yui3-slider-content yui3-slider-x"><!-- or slider-y -->

          <!-- rail -->
          <span class="yui3-slider-rail">
              <span class="yui3-slider-rail-cap-left"></span><!-- or cap-top -->
              <span class="yui3-slider-rail-cap-right"></span><!-- or cap-bottom -->

              <!-- thumb -->
              <span class="yui3-slider-thumb">
                  <img class="yui3-slider-thumb-shadow">
                  <img class="yui3-slider-thumb-image">
              </span>
          </span>

      </span>
  </span>

</div>

introductions/templates/introductions/_introduction_item.html
    {% if not object.followup_set.requested %}
    <div class="panel callout radius">
        <p>Requesting feedback from {{ object.introducee1 }} and {{ object.introducee2 }} will help you understand what really happens because of your intros - and learn how and for whom to make even better intros.</p>
        <p>You can customise the email on the next page.</p>
        <a href="#" class="button medium">Ask for Feedback</a>
    </div>
    {% endif %}
    {% if object.followup_set.commented %}
    <a id="feedback"><h1>Your Feedback!</h1></a>
    {% endif %}
    {% for followup in  object.followup_set.commented %}
    <article>
        <h3>{{ followup.added|timesince }} ago </h3>
          <section class="summary">
            <span class="triangle-top"></span>
            <h4 class="type">Feedback added by {{ followup.email }}</h4>
            <p class="date">{{ followup.added }}</p>
            <div class="avatar"><img src="/images/icon-person.png" alt=""></div>
            <div class="body">
              <div class="message">
                  {{followup.comment|linebreaks}}
              </div>
          </section>
    </article>
    {% endfor %}
    {% for followup in  object.followup_set.requested %}
    <article>
        <h3>{{ followup.requested|timesince }} ago </h3>
          <section class="summary">
            <span class="triangle-top"></span>
            <h4 class="type">Feedback requested from {{ followup.email }}</h4>
            <p class="date">{{ followup.requested }}</p>
          </section>
    </article>
    {% endfor %}
    <article>
          <h3>{{ object.created|timesince }} ago</h3>
          <section class="summary">
            <span class="triangle-top"></span>
            <h4 class="type">Intro made</h4>
            <div class="avatar"><img src="/images/icon-person.png" alt=""></div>
            <div class="body">
                <h5 class="subject">{{ object.subject }}</h5>
              <p class="date">{{ object.created }}</p>
              <div class="message">
                  {{object.message|linebreaks}}
              </div>
            </div>
          </section>
    </article>

introductions/templates/introductions/_introduction_list_item.html
<article class="introduction">

      <div class="top">
          <span class="info">{{ object.created|timesince }} ago</span>
      </div>

      <div class="row">
        <div class="nine columns">
          
          <div class="row person-container">
            <div class="five columns">
              
              <div class="person">
                <span class="image"><img src="/images/icon_person.png" alt=""></span>
                <h1 class="name">{{ object.introducee1 }}</h1>
              </div>

            </div>
            <div class="one columns person-seperator">
          
            </div>
            <div class="five columns end">
              
              <div class="person">
                <span class="image"><img src="/images/icon_person.png" alt=""></span>
                <h1 class="name">{{ object.introducee2 }}</h1>
              </div>

            </div>
          </div>

          <div class="row">
            <div class="twelve columns">
              
              <div class="message">
 

                  <h2 class="subject">{{ object.subject|truncatewords:5 }}</h2>
                  <div class="date">{{ object.created }}</div>
                    <div class="message-content">
                        {{ object.message|truncatewords:10 }}
                        <br />
                        <br />
                        <a href="{{ object.get_user_url }}" class="details">View Full History »</a>
                        <br />
                        <br />
                    </div>


              </div>

            </div>
          </div>

        </div>
        <div class="three columns">
          
          <div class="aside">

              <h4 class="title">What they've said</h4>
          {% if object.followup_set.commented %}
          {% for feedback in object.followup_set.commented %}
          {% if feedback.comment %}
          <div class="row">
            <div class="twelve columns">
                <p>"{{ feedback.comment }}"</p><p>{{feedback.email}}</cite></p>
            {% comment %}
              <ul class="link-list">
                <li><a href="">Comment</a></li>
                <li><a href="">Share</a></li>
              </ul>
              {% endcomment %}
            </div>
          </div>
          {% endif %}
          {% endfor %}
          {% else %}
          <div class="row">
            <div class="twelve columns ">
                <p>Nothing yet...</p>
              <a class="medium button radius" href="{{ object.get_user_url }}/notify">Request Feedback</a>
            </div>
          </div>
          {% endif %}
            

          </div>

        </div>

      </div>

</article>

introductions/templates/introductions/feedback_form.html
{% extends 'base.html' %}
{% block title %}How excited are you?{% endblock %}
{% block topbar %}
{% include "partials/top_bar_simple.html" %}
{% endblock %}
{% block body_id %}feedback{% endblock %}
{% block content %}
<header>
  <div class="row">
    <div id="salute">
      
      <h1>Hi {{ object.email}}!</h1>
      <hr />

      <div class="salutation">
          <p>{{ object.introduction.created|timesince }} ago, I introduced you to {{ object.other_email }}</p>
        <p>Please tell me how it went so I can make better intros for you next time!</p>
      </div>
      <hr />

    <h3 class="subheader">Message Contents</h3>
    <h4>{{ object.introduction.subject }}</h4>
      <div class="intro-summary closed">
        <p>
        {{ object.introduction.clean_message|linebreaksbr }}
        </p>
      </div>
        <a href="#" class="seemore">Show/Hide Message</a>
        <br />
        <br />
      <span class="triangle-bottom"></span>
    </div>
  </div>
</header>
<!-- /header -->

<div id="feedback-form">
  <div class="row">
    <div id="form-content">
      
  <h2>How excited are you about this intro?</h2>

  <h5>click the bar</h5>
  <div id="excited-slider" class="noUiSlider horizontal-big"></div>

  
  <h3 id="slider-big-title"><img src="/images/icon-smiley.png" alt=""> I am <strong>super excited</strong> about this intro!</h3>
  
<form  method="post" id="Feedback" class="custom">
    {% csrf_token %}
  <textarea rows="4" cols="50" placeholder="Add a comment (optional)"></textarea>

  <h4>If it's helped, please tell me how:<small>Select all that apply (optional)</small></h4>

    <div class="row">
      <div class="options">
    <label for="recruiting">
      <input name="recruiting" type="checkbox" id="id_recruiting" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-network-orange.png" alt=""> Recruiting
    </label>
  </div>
      <div class="options">
    <label for="partnerships">
      <input name="partnerships" type="checkbox" id="id_partnerships" style="display:none;">
      <span class="custom checkbox"></span>  <img src="/images/icon-partnership.png" alt=""> Partnership
    </label>
  </div>
      <div class="options">
    <label for="sales">
      <input name="sales" type="checkbox" id="id_sales" style="display:none;">
      <span class="custom checkbox"></span>  <img src="/images/icon-check.png" alt=""> Sales
    </label>
  </div>
    </div>
    <div class="row">
      <div class="options">
    <label for="networking">
      <input name="networking" type="checkbox" id="id_networking" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-network-orange.png" alt=""> Networking</label>
  </div>
      <div class="options">
    <label for="fundraising">
      <input name="fundraising" type="checkbox" id="id_fundraising" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-check.png" alt=""> Raising Funds
    </label>
  </div>
      <div class="options">
    <label for="mentorship">
      <input name="mentorship" type="checkbox" id="id_mentorship" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-cloud.png" alt=""> Mentorship
    </label>
  </div>
    </div>
    <div class="row">
      <div class="options">
    <label for="other">
      <input name="other" type="checkbox" id="id_other" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-network-orange.png" alt=""> Other
    </label>
  </div>
      <div class="options left">
    <label for="toosoon">
      <input name="toosoon" type="checkbox" id="id_toosoon" style="display:none;">
      <span class="custom checkbox"></span> <img src="/images/icon-partnership.png" alt=""> Too soon to tell
    </label>
  </div>
    </div>
    <hr />
<div class="row">
<div class="form-button">  
    <input type=submit class="button expand" />
  </div>
</div>

{{ form.rating }}
</form>
</div>
</div>
</div>

<footer>
  <div class="row">
    <div class="invite-now">
      <p>Also want to use <strong>intros.to</strong> to track your intros? <strong>Request an invite now!</strong></p>
    </div>
  </div>
</footer>
{% endblock %}
{% block pagejs %}
 <script>
$(".seemore").click(function() { 
    $('.intro-summary.closed').slideDown('slow', function(){$(this).addClass('open').removeClass('closed')}); 
    $('.intro-summary.open').slideUp('slow', function(){$(this).addClass('closed').removeClass('open')}); 
});

    // slider
    $("#excited-slider").noUiSlider({
      range: [1, 1000],
      start: 750,
      handles: 1,
      step: 1
    });

    // update expression
    $(document).on('change', '#excited-slider', function() {

      var currentValue = $('#excited-slider input').val();
      var newValue;
      $("#id_rating").val(parseInt(currentValue/10));
      console.log($("#id_rating").val());
       
      if ((currentValue >= 1) && (currentValue <= 250)) {
        newValue = 'not excited';
      }
      else if ((currentValue > 250) && (currentValue <= 500)) {
        newValue = 'not sure';
      }
      else if ((currentValue > 500) && (currentValue <= 750)) {
        newValue = 'pretty excited';
      }
      else if ((currentValue > 750) && (currentValue <= 1000)) {
        newValue = 'super excited';
      }

      $('#slider-big-title strong').html(newValue);
    });

  </script>
{% endblock %}

introductions/templates/introductions/followup_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block header %}
<div class="heading-section">
  <div class="row">
    <div class="twelve columns">
    <h1>
          <span class="large">Hi {{ object.email }}</span><a href="#Feedback">
      </h1>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="twelve column">
        <div class="section new-section diagonal-dash introductions">  
          <div class="row">
            <div class="twelve columns">
              <div class="row introduction-date">
                <div class="twelve columns">
                  <h3 class="large date">{{ object.introduction.connector.get_full_name }} introduced you {{ object.introduction.created|timesince }} ago</h3>
                </div>
              </div>
              <article class="introduction">
                <div class="message">
                  <span class="profile-image"><img src="/images/icon_person.png" alt=""></span>
                  <h2 class="subject">{{ object.introduction.subject }}</h2>
                  <div class="date">{{ object.introduction.created }}</div>
                  <div class="message-content">
                    {{ object.introduction.message|linebreaks }}
                  </div>
                </div>
               </article>
              <div class="row introduction-date">
                <div class="ten columns centered">
                      <h3 class="large date">What's happened because of this?</h3>
                  </div>
              </div>
              <article class=introduction>
                  <div class="outcomes">
                    <form  method="post" id="Feedback">
                        {% csrf_token %}
                        <br />
                        <br />
                          <div class="row collapse">
                              <div class="two columns"> {{ form.name.label_tag }}</div>
                              <div class="ten columns">{{ form.name|add_error_class:"error" }}
                              {% for error in form.name.errors %}
                                  <small class=error>{{ error }}</small>
                              {% endfor %}
                              </div>
                          </div>
                          <div class="row collapse">
                              <div class="two columns"> {{ form.email.label_tag }}</div>
                              <div class="ten columns">{{ form.email|add_error_class:"error" }}
                              {% for error in form.email.errors %}
                                  <small class=error>{{ error }}</small>
                              {% endfor %}
                              </div>
                          </div>
                          <label>Was it appropriate? Interesting? Has something cool come of it?</label>
                          {{ form.comment|attr:"rows:4"|add_error_class:"error" }}
                          {% for error in form.comment.errors %}
                              <small class=error>{{ error }}</small>
                          {% endfor %}
                          {{ form.rating }}
                      <button type="submit" class="radius button">Submit</button>
                      </form>
                  </div>
              </article>
                </div>
            </div>
          </div>
      </div>
    </div>
    {% endblock %}